[package]
name = "overlayterm"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-autostart = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
portable-pty = "0.9.0"
log = "0.4.29"
tauri-plugin-global-shortcut = "2.3.1"
tauri-plugin-store = "2.4.2"
tauri-plugin-shell = "2.3.5"
window-vibrancy = "0.6"
dirs = "6.0.0"
arboard = "3.6.1"
base64 = "0.22.1"
image = "0.25.8"
xcap = "0.9.1"

[dev-dependencies]
tokio  = { version = "1", features = ["full"] }
tempfile = "3"

[target.'cfg(target_os = "windows")'.dependencies]
file-opening = { path = "../crates/file-opening" }
file-opening-windows = { path = "../crates/file-opening-windows" }
windows-sys = { version = "0.59", features = [
  "Win32_Storage_FileSystem",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }

[target.'cfg(target_os = "macos")'.dependencies]
file-opening = { path = "../crates/file-opening" }
file-opening-macos = { path = "../crates/file-opening-macos" }
