/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! Kernel launch infrastructure with rust-analyzer type hint support.
//!
//! This module provides traits and helpers for launching CUDA kernels with
//! full IDE type checking. The key insight is separating concerns:
//!
//! - **Macro** (`cuda_launch!`): Captures kernel identifier → PTX name string,
//!   marshals arguments into a `Vec<*mut c_void>`, and calls
//!   `cuda_core::launch_kernel` directly.
//! - **Traits** (`CudaKernel`, `GenericCudaKernel`): Provide PTX entry-point
//!   names for rust-analyzer and compile-time validation.

// =============================================================================
// Core Traits
// =============================================================================

/// Trait implemented by kernel functions.
///
/// This trait is automatically generated by the `#[kernel]` attribute macro.
/// It provides the PTX entry point name for runtime kernel lookup.
///
/// # Example
///
/// When you write:
/// ```ignore
/// #[kernel]
/// pub fn vecadd(a: &[f32], b: &[f32], mut c: DisjointSlice<f32>) { ... }
/// ```
///
/// The macro generates (on host side only):
/// ```ignore
/// pub struct __vecadd_CudaKernel;
/// impl CudaKernel for __vecadd_CudaKernel {
///     const PTX_NAME: &'static str = "vecadd";  // Original function name
/// }
/// ```
///
/// Note: the function is renamed internally to `cuda_oxide_kernel_<hash>_vecadd`
/// for detection by the compiler backend (the prefix is owned by the
/// workspace-internal `reserved-oxide-symbols` crate), but the PTX entry point
/// uses the original name.
pub trait CudaKernel {
    /// The PTX entry point name (e.g., "vecadd" - the original function name)
    const PTX_NAME: &'static str;
}

/// Trait for generic kernel functions.
///
/// Unlike `CudaKernel`, this trait provides a function to get the PTX name
/// because generic kernels have different PTX names for each type instantiation.
///
/// # Example
///
/// For a generic kernel:
/// ```ignore
/// #[kernel]
/// pub fn scale<T: Copy + Mul<Output = T>>(factor: T, input: &[T], mut out: DisjointSlice<T>) { ... }
/// ```
///
/// The macro generates:
/// ```ignore
/// pub struct __scale_CudaKernel<T>(std::marker::PhantomData<T>);
///
/// impl<T: Copy + Mul<Output = T>> GenericCudaKernel for __scale_CudaKernel<T> {
///     fn ptx_name() -> &'static str {
///         // Hash-based name that matches what the backend generates
///         // e.g., "scale_a1b2c3d4" for scale::<f32>
///     }
/// }
/// ```
///
/// # PTX Naming Scheme
///
/// Generic kernels use a hash of `std::any::type_name::<Self>()` to generate
/// a stable, unique PTX name for each instantiation. The backend uses the same
/// scheme when generating PTX.
pub trait GenericCudaKernel {
    /// Get the PTX entry point name for this specific instantiation.
    ///
    /// Unlike `CudaKernel::PTX_NAME`, this is a function because the name
    /// depends on the type parameters.
    fn ptx_name() -> &'static str;
}

// =============================================================================
// Argument Wrapper Types
// =============================================================================

/// Wrapper for scalar values that need to be passed to kernels.
///
/// This wrapper exists for documentation purposes and to make the intent clear.
/// The macro handles unwrapping these properly.
///
/// # Example
///
/// ```ignore
/// cuda_launch! {
///     kernel: scale,
///     // ...
///     args: (Scalar(factor), &input_dev, &mut output_dev)
/// }
/// ```
pub struct Scalar<T>(pub T);

/// Wrapper indicating a device buffer is read-only in the kernel.
///
/// # Example
///
/// ```ignore
/// cuda_launch! {
///     kernel: transform,
///     // ...
///     args: (ReadOnly(&input_dev), &mut output_dev)
/// }
/// ```
pub struct ReadOnly<'a, T>(pub &'a T);

/// Wrapper indicating a device buffer is write-only in the kernel.
///
/// This is a hint for future optimizations - currently treated same as mutable.
///
/// # Example
///
/// ```ignore
/// cuda_launch! {
///     kernel: generate,
///     // ...
///     args: (WriteOnly(&mut output_dev),)
/// }
/// ```
pub struct WriteOnly<'a, T>(pub &'a mut T);

// =============================================================================
// Length Extraction (for slice kernels)
// =============================================================================

/// Trait for types that have a length (used to pass ptr+len to kernels).
pub trait HasLength {
    fn len(&self) -> usize;
    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl<T> HasLength for cuda_core::DeviceBuffer<T> {
    fn len(&self) -> usize {
        self.len()
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // Dummy kernel marker for testing
    struct TestKernelMarker;
    impl CudaKernel for TestKernelMarker {
        const PTX_NAME: &'static str = "test_kernel"; // Original function name
    }

    #[test]
    fn test_ptx_name_lookup() {
        assert_eq!(TestKernelMarker::PTX_NAME, "test_kernel");
    }

    #[test]
    fn test_scalar_wrapper() {
        let s = Scalar(42i32);
        assert_eq!(s.0, 42);
    }
}
