<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="8" y="18" width="8" height="10" fill="#BB93B3"/>
  <path d="M12 18 L12 8 L20 8 L20 12 L24 12 L24 16 L20 16 L20 18" fill="#BB93B3"/>
  <circle cx="22" cy="10" r="1.5" fill="#D3C1A9"/>
</svg>