/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! Cross-Crate Kernel Example
//!
//! This example tests the ability to use kernels defined in a library crate.
//!
//! ## Structure
//!
//! ```text
//! cross_crate_kernel/
//! ├── Cargo.toml          # Binary crate (this file)
//! ├── src/main.rs         # Uses kernels from kernel-lib
//! └── kernel-lib/         # Library crate
//!     ├── Cargo.toml
//!     └── src/lib.rs      # Defines #[kernel] functions
//! ```
//!
//! ## What This Tests
//!
//! 1. Generic kernels defined in external crate (`kernel_lib::scale<T>`)
//! 2. Monomorphization at use site (`scale::<f32>` instantiated here)
//! 3. PTX generation for cross-crate kernels
//! 4. Device helper functions from external crates
//!
//! ## Build and Run
//!
//! ```bash
//! cargo oxide run cross_crate_kernel
//! ```

use cuda_core::{CudaContext, DeviceBuffer, LaunchConfig};
use cuda_host::cuda_launch;

// Import everything from the kernel library!
// This includes the #[kernel] functions and their generated helpers:
// - scale, add, scale_with_helper (original functions)
// - cuda_oxide_kernel_<hash>_* (renamed entry points; the prefix is owned
//   by `crates/reserved-oxide-symbols/` so this crate isn't a load-bearing
//   string-literal site)
// - __*_CudaKernel (marker types for CudaKernel trait)
use kernel_lib::*;

fn main() {
    println!("=== Cross-Crate Kernel Test ===\n");
    println!("Testing kernels defined in kernel-lib crate.\n");

    // Initialize CUDA
    let ctx = CudaContext::new(0).expect("Failed to create CUDA context");
    let stream = ctx.default_stream();

    // Load PTX (generated by rustc-codegen-cuda)
    // The PTX contains all monomorphized kernels from both crates
    let module = ctx
        .load_module_from_file("cross_crate_kernel.ptx")
        .expect("Failed to load PTX module");

    // Test data
    const N: usize = 1024;

    // =========================================================================
    // Test 1: Generic scale kernel from library (f32)
    // =========================================================================
    println!("Test 1: kernel_lib::scale::<f32>");
    {
        let factor: f32 = 2.5;
        let input: Vec<f32> = (0..N).map(|i| i as f32).collect();

        let input_dev = DeviceBuffer::from_host(&stream, &input).unwrap();
        let mut output_dev = DeviceBuffer::<f32>::zeroed(&stream, N).unwrap();

        cuda_launch! {
            kernel: scale::<f32>,
            stream: stream,
            module: module,
            config: LaunchConfig::for_num_elems(N as u32),
            args: [factor, slice(input_dev), slice_mut(output_dev)]
        }
        .expect("Kernel launch failed");

        let output: Vec<f32> = output_dev.to_host_vec(&stream).unwrap();

        let errors = (0..N)
            .filter(|&i| (output[i] - input[i] * factor).abs() > 1e-5)
            .count();

        if errors == 0 {
            println!("  ✓ PASSED: scale::<f32> from library works!\n");
        } else {
            println!("  ✗ FAILED: {} errors\n", errors);
            std::process::exit(1);
        }
    }

    // =========================================================================
    // Test 2: Generic scale kernel from library (i32)
    // =========================================================================
    println!("Test 2: kernel_lib::scale::<i32>");
    {
        let factor: i32 = 3;
        let input: Vec<i32> = (0..N as i32).collect();

        let input_dev = DeviceBuffer::from_host(&stream, &input).unwrap();
        let mut output_dev = DeviceBuffer::<i32>::zeroed(&stream, N).unwrap();

        cuda_launch! {
            kernel: scale::<i32>,
            stream: stream,
            module: module,
            config: LaunchConfig::for_num_elems(N as u32),
            args: [factor, slice(input_dev), slice_mut(output_dev)]
        }
        .expect("Kernel launch failed");

        let output: Vec<i32> = output_dev.to_host_vec(&stream).unwrap();

        let errors = (0..N).filter(|&i| output[i] != input[i] * factor).count();

        if errors == 0 {
            println!("  ✓ PASSED: scale::<i32> from library works!\n");
        } else {
            println!("  ✗ FAILED: {} errors\n", errors);
            std::process::exit(1);
        }
    }

    // =========================================================================
    // Test 3: Generic add kernel from library
    // =========================================================================
    println!("Test 3: kernel_lib::add::<f32>");
    {
        let a: Vec<f32> = (0..N).map(|i| i as f32).collect();
        let b: Vec<f32> = (0..N).map(|i| (i * 2) as f32).collect();

        let a_dev = DeviceBuffer::from_host(&stream, &a).unwrap();
        let b_dev = DeviceBuffer::from_host(&stream, &b).unwrap();
        let mut c_dev = DeviceBuffer::<f32>::zeroed(&stream, N).unwrap();

        cuda_launch! {
            kernel: add::<f32>,
            stream: stream,
            module: module,
            config: LaunchConfig::for_num_elems(N as u32),
            args: [slice(a_dev), slice(b_dev), slice_mut(c_dev)]
        }
        .expect("Kernel launch failed");

        let c: Vec<f32> = c_dev.to_host_vec(&stream).unwrap();

        let errors = (0..N)
            .filter(|&i| (c[i] - (a[i] + b[i])).abs() > 1e-5)
            .count();

        if errors == 0 {
            println!("  ✓ PASSED: add::<f32> from library works!\n");
        } else {
            println!("  ✗ FAILED: {} errors\n", errors);
            std::process::exit(1);
        }
    }

    // =========================================================================
    // Test 4: Kernel that uses device helper function from library
    // =========================================================================
    println!("Test 4: kernel_lib::scale_with_helper::<f32> (uses device helper)");
    {
        let factor: f32 = 4.0;
        let input: Vec<f32> = (0..N).map(|i| i as f32).collect();

        let input_dev = DeviceBuffer::from_host(&stream, &input).unwrap();
        let mut output_dev = DeviceBuffer::<f32>::zeroed(&stream, N).unwrap();

        cuda_launch! {
            kernel: scale_with_helper::<f32>,
            stream: stream,
            module: module,
            config: LaunchConfig::for_num_elems(N as u32),
            args: [factor, slice(input_dev), slice_mut(output_dev)]
        }
        .expect("Kernel launch failed");

        let output: Vec<f32> = output_dev.to_host_vec(&stream).unwrap();

        let errors = (0..N)
            .filter(|&i| (output[i] - input[i] * factor).abs() > 1e-5)
            .count();

        if errors == 0 {
            println!("  ✓ PASSED: scale_with_helper uses device function from library!\n");
        } else {
            println!("  ✗ FAILED: {} errors\n", errors);
            std::process::exit(1);
        }
    }

    println!("=== All Cross-Crate Tests Passed! ===");
    println!("\nThis demonstrates:");
    println!("  - Generic kernels can be defined in library crates");
    println!("  - They are monomorphized when used in the application");
    println!("  - PTX is generated for all used instantiations");
    println!("  - Device helper functions from libraries also work");
}
