/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// AUTO-GENERATED by crates/fuzzer/tools/mir_generator.py.
// rustlantis seed: 19
// Adapted dump calls update the fuzzer crate's global trace state.

#![allow(unused_assignments, unused_parens, overflowing_literals)]

use core::intrinsics::mir::*;
use fuzzer::{dump_var, trace_finish, trace_reset};

#[custom_mir(dialect = "runtime", phase = "initial")]
fn fn1(mut _1: u64, mut _2: i8, mut _3: isize) -> isize {
    mir! {
        type RET = isize;
        let __rl_dump0: (u64, i8, isize);
        let _4: u64;
        let _5: ();
        let _6: ();
        {
            _2 = !(-104_i8);
            _3 = 3_usize as isize;
            _3 = !(-2_isize);
            RET = 325053091788252758_u64 as isize;
            _1 = 3827336996332977442_u64 | 1462025685715739877_u64;
            _3 = RET ^ RET;
            Call(RET = core::intrinsics::transmute(_3), ReturnTo(bb1), UnwindUnreachable())
        }
        bb1 = {
            _1 = 9110680626090339370_u64 >> _2;
            Goto(bb2)
        }
        bb2 = {
            _1 = !4656692005594089594_u64;
            Goto(bb3)
        }
        bb3 = {
            __rl_dump0 = (Move(_1), Move(_2), Move(_3));
            Call(_5 = dump_var(Move(__rl_dump0)), ReturnTo(bb4), UnwindUnreachable())
        }
        bb4 = {
            Return()
        }
    }
}

#[inline(never)]
pub fn compute_rustlantis_trace() -> u64 {
    trace_reset();
    let _ = fn1(10_u64, (-17_i8), 42_isize);
    trace_finish()
}
