<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x="0" y="0" width="32" height="32" fill="#0D0D0D" stroke="none" stroke-width="2"/>
  <rect x="6" y="18" width="10" height="10" fill="#CC00FF" stroke="none" stroke-width="0"/>
  <path d="M 10 18 L 10 8 L 20 8 L 20 12 L 26 12 L 26 16 L 20 16 L 20 18 Z" fill="#CC00FF" stroke="#F0F0F0" stroke-width="0" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
